# Generated by Django 4.2.7 on 2024-02-23 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usershome', '0007_alter_customuser_phone_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_no',
        ),
    ]
