version: "3.9"
services:
 db:
  image: postgres:latest
  volumes:
   - postgres_data:/var/lib/postgresql/data/
  ports:
   - 5432:5432
  env_file:
   - .env

 app:
  build: .
  volumes:
   - .:/bestview
  ports:
   - 8000:8000
  image: app:bestview
  container_name: bestview_proj_container
  depends_on:
   - db
  command: python manage.py runserver 0.0.0.0:8000
  env_file:
   - .env 

volumes:
 postgres_data: