# Generated by Django 4.2.7 on 2024-02-17 06:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminproductmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(unique=True)),
                ('orderdate', models.DateField(auto_now_add=True)),
                ('total', models.IntegerField()),
                ('paymentmethod', models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Razor Pay', 'Razor Pay'), ('Wallet', 'Wallet')])),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_or_building_name', models.CharField()),
                ('street_address', models.CharField()),
                ('city', models.CharField()),
                ('district', models.CharField()),
                ('pincode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message="Pincode must be 6 'digits'", regex='^\\d{6}$')])),
                ('state', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('deliverydate', models.DateField()),
                ('order_status', models.CharField(choices=[('Pending', 'Pending'), ('Dispatched', 'Dispatched'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_order_and_payment.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminproductmanagement.product')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminproductmanagement.productvariant')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='orderaddress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_order_and_payment.orderaddress'),
        ),
    ]
