# Generated by Django 4.2.7 on 2024-02-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_order_and_payment', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentmethod',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('PayPal', 'PayPal'), ('Wallet', 'Wallet')]),
        ),
    ]
