# Generated by Django 4.2.7 on 2024-02-24 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_order_and_payment', '0006_alter_orderaddress_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Refunded', 'Refunded'), ('Paid', 'Paid')], default='Paid'),
            preserve_default=False,
        ),
    ]
