# Generated by Django 5.0.1 on 2024-02-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_order_and_payment', '0009_alter_orderitems_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Refunded', 'Refunded'), ('Paid', 'Paid')]),
        ),
    ]
