# Generated by Django 5.0.1 on 2024-02-26 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_order_and_payment', '0013_alter_orderitems_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Dispatched', 'Dispatched'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned')], default='Pending'),
        ),
    ]
