# Generated by Django 5.0.1 on 2024-03-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_order_and_payment', '0014_alter_orderitems_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='deliverydate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
