# Generated by Django 5.0.1 on 2024-03-17 15:43

import user_order_and_payment.models
from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user_order_and_payment', '0015_alter_orderitems_deliverydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderaddress',
            name='pincode',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message="Pincode must be 6 'digits'", regex='^\\d{6}$')]),
        ),
    ]
