# Generated by Django 5.0.1 on 2024-03-17 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_order_and_payment', '0016_alter_orderaddress_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderaddress',
            name='pincode',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message="Pincode must be 6 'digits'", regex='^\\d{6}$')]),
        ),
    ]
