# Generated by Django 4.2.7 on 2024-02-17 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('image', models.ImageField(upload_to='brand_image/')),
                ('is_listed', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('image', models.ImageField(upload_to='category_image/')),
                ('is_listed', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('description', models.TextField()),
                ('type', models.CharField()),
                ('price', models.IntegerField()),
                ('thumbnail', models.ImageField(upload_to='product_thumbnail/')),
                ('is_listed', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminproductmanagement.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminproductmanagement.category')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField()),
                ('quantity', models.IntegerField()),
                ('thumbnail', models.ImageField(upload_to='product_variant_thumbnail/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminproductmanagement.product')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_variant_image/')),
                ('productvariant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminproductmanagement.productvariant')),
            ],
        ),
    ]
