# Generated by Django 5.0.1 on 2024-03-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminproductmanagement', '0005_alter_coupons_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('used', 'Used'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
