# Generated by Django 5.0.1 on 2024-03-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminproductmanagement', '0006_coupons_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Redeemed', 'Redeemed'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
    ]
