# Generated by Django 5.0.1 on 2024-03-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminproductmanagement', '0007_alter_coupons_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='code',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
