# Generated by Django 5.0.1 on 2024-03-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminproductmanagement', '0008_alter_coupons_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupons',
            name='discount_amount',
        ),
        migrations.AddField(
            model_name='coupons',
            name='discount_percentage',
            field=models.IntegerField(default=20, max_length=3),
            preserve_default=False,
        ),
    ]
