# Generated by Django 5.0.1 on 2024-03-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminproductmanagement', '0009_remove_coupons_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='discount_percentage',
            field=models.IntegerField(),
        ),
    ]
