# Generated by Django 5.0.1 on 2024-03-10 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminproductmanagement', '0011_alter_coupons_status_usedcoupons'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupons',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='usedcoupons',
            options={'ordering': ['-id']},
        ),
    ]
