# Generated by Django 5.0.1 on 2024-03-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminproductmanagement', '0013_categoryoffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryoffer',
            name='status',
        ),
        migrations.AddField(
            model_name='categoryoffer',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
    ]
