# Generated by Django 5.0.1 on 2024-03-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminproductmanagement', '0015_alter_categoryoffer_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoffer',
            name='discount_percentage',
            field=models.IntegerField(),
        ),
    ]
