# Generated by Django 5.0.1 on 2024-03-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminproductmanagement', '0016_alter_categoryoffer_discount_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryoffer',
            name='is_listed',
        ),
        migrations.AddField(
            model_name='categoryoffer',
            name='status',
            field=models.CharField(default='Active', max_length=10),
        ),
    ]
