# Generated by Django 5.0.1 on 2024-03-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminproductmanagement', '0018_product_offer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer_price',
            field=models.IntegerField(null=True),
        ),
    ]
