# Generated by Django 5.0.1 on 2024-03-11 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminproductmanagement', '0019_alter_product_offer_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.IntegerField()),
                ('valid_from', models.DateField(auto_now_add=True)),
                ('valid_to', models.DateField()),
                ('status', models.CharField(default='Active', max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminproductmanagement.category')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
