# Generated by Django 5.0.1 on 2024-03-11 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminproductmanagement', '0020_productoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoffer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminproductmanagement.product'),
        ),
    ]
