# Generated by Django 5.0.1 on 2024-03-20 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminproductmanagement', '0022_alter_categoryoffer_category_and_more'),
        ('user_order_and_payment', '0017_alter_orderaddress_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedcoupons',
            name='item',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='user_order_and_payment.orderitems'),
            preserve_default=False,
        ),
    ]
