# Generated by Django 5.0.1 on 2024-03-20 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminproductmanagement', '0023_usedcoupons_item'),
        ('userproduct', '0004_wishlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedcoupons',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userproduct.cartitem'),
        ),
    ]
