# Generated by Django 5.0.1 on 2024-03-20 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminproductmanagement', '0024_alter_usedcoupons_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usedcoupons',
            name='item',
        ),
    ]
