# Generated by Django 4.2.7 on 2024-02-17 06:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_or_building_name', models.CharField()),
                ('street_address', models.CharField()),
                ('city', models.CharField()),
                ('district', models.CharField()),
                ('pincode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message="Pincode must be 6 'digits'", regex='^\\d{6}$')])),
                ('state', models.CharField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
