# Generated by Django 4.2.7 on 2024-02-23 10:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone_no',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be 10 'digits'", regex='^\\d{10}$')]),
        ),
    ]
