# Generated by Django 4.2.7 on 2024-02-23 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_address_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone_no',
            field=models.CharField(default=4732759884, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be 10 'digits'", regex='^\\d{10}$')]),
            preserve_default=False,
        ),
    ]
