# Generated by Django 5.0.1 on 2024-03-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_alter_wallettransactions_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransactions',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
