# Generated by Django 5.0.1 on 2024-03-06 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_alter_wallettransactions_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallettransactions',
            options={'ordering': ['-id']},
        ),
    ]
