# Generated by Django 5.0.1 on 2024-03-06 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0012_alter_wallettransactions_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallettransactions',
            options={},
        ),
    ]
